//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Bundles.Minification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentStyle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentStyle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Custom.Bundles.Minification.ContentStyle", typeof(ContentStyle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    padding-top: 50px;
        ///    padding-bottom: 20px;
        ///}
        ///
        ////* Set padding to keep content from hitting the edges */
        ///.body-content {
        ///    padding-left: 15px;
        ///    padding-right: 15px;
        ///}
        ///
        ////* Override the default bootstrap behavior where horizontal description lists 
        ///   will truncate terms that are too long to fit in the left column 
        ///*/
        ///.dl-horizontal dt {
        ///    white-space: normal;
        ///}
        ///
        ////* Set width on the form input elements since they&apos;re 100% wide by default */
        ///input,
        ///select,
        ///textarea {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
    }
}
